### PR TITLE
Remove asct-b/ref-organ docs

### PR DESCRIPTION
**Pull request by mccalluc**
Katy said these are not actually needed, and the DOIs will reference github instead?

### CODE REVIEW

**Comment by lecross** [comment]
Hi Chuck,

Yes, yesterday it was determined that we create our own GitHub repo for the purpose of managing files associated with the DOI process. Sorry for all the unnecessary effort on your end. The DOIs will reference this new repo.

Thanks again for the help.


________________________________
From: Chuck McCallum ***@***.***>
Sent: Friday, March 26, 2021 8:13 AM
To: hubmapconsortium/portal-docs ***@***.***>
Cc: Cross, Leonard Edward ***@***.***>; Review requested ***@***.***>
Subject: [hubmapconsortium/portal-docs] Remove asct-b/ref-organ docs (#60)


Katy said these are not actually needed, and the DOIs will reference github instead?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/hubmapconsortium/portal-docs/pull/60

Commit Summary

  *   Katy said these are not actually needed, and the DOIs will reference github instead?

File Changes

  *   D asct-b/bone-marrow-and-blood.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-4e314a3de08de130605da55e875f0a4e758448b2017dc8f0d25d42714158ecca> (20)
  *   D asct-b/brain.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-2283d777f301a40ad9b34113e7c6b56a94cb3dc47cfbc07b0454ccb753f59b85> (20)
  *   D asct-b/heart.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-063b7060b2d233f1623abc19609f81f1a43c4d80558ce7ccdb69f7217fe29f5d> (20)
  *   D asct-b/intestine-large.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-083885a35bb69c0bbaa3fa5602194eb8fa71e92658eead2cc4977c804361dc69> (20)
  *   D asct-b/kidney.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-16f4d0d120d47381546acf5ba479dddee1cf56c84e8ed64d2ca74f107fc251af> (20)
  *   D asct-b/lung.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-7905ee5cdc41b239e7953af180cfabe9b396b7e639a67c852d0648ec13fd03a5> (20)
  *   D asct-b/lymph-node.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-d5572affaed07057ee2942be10ad00d199d0a2f691b65d73fa5c74b9667135cb> (20)
  *   D asct-b/readme.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-7c3807d36c92da99bfa4e3de69c438f7f1b812fa519beba9d6063ca3e99476fd> (1)
  *   D asct-b/skin.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-641db8bde120752153f5f5f8d5f2b2baa404ae4ac0b98d8f39d9c0e68ae63a2b> (20)
  *   D asct-b/spleen.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-9a508b64bf8ea97fb3fa3e739d775428f74d7bb657f4a5a22ffbdd6339760a9b> (20)
  *   D asct-b/thymus.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-6ffbf3bb63b83f2f964dff714fde26c4e4a4d343bd7c598cc939ac6ef48a8076> (20)
  *   D asct-b/vasculature.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-bbe621b6b99f8f5d2602969c38a26704acf2eaf4acf573edacc2ed4cb0c1f919> (20)
  *   D ref-organs/brain-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-6330ec941779c0542dc17edfbc49651eb2ec04eacdbcb935b21607cafb1e6dd5> (20)
  *   D ref-organs/brain-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-191ec4b9f071b2fe74d32002a4b3672b86955d95c025e76d53950d29dda9b8b7> (20)
  *   D ref-organs/heart-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-238ba45d1262375f176fab6aa555f956f76250ce36a55276069c8b91ce520b43> (20)
  *   D ref-organs/heart-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-6f955594b5b39b54f8ecd9096d07095ea401b006304d353db54e634591f2eba6> (20)
  *   D ref-organs/intestine-large-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-d89cbc2bb9458be90ebf65ca4b786db3e61c6d7af4e7832101cf410369e58a29> (20)
  *   D ref-organs/intestine-large-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-af4e442636caaada698cc361e6b794e68c4c47b0323b56a03e11cc52f2f94ac2> (20)
  *   D ref-organs/kidney-female-left.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-8c2c71de181a6ae6fa1c039e4d1337753097de3da185f485ec0e3bebe218ded3> (20)
  *   D ref-organs/kidney-female-right.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-b2abfd2dc5da2846cf7b878edaca10d0a7cef884d1c602f0f1482b102eb1e4f1> (20)
  *   D ref-organs/kidney-male-left.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-5a4a2bc42aabe7a7bd3be6ba60b8df3ad73c6f5aa789c0520c5960a038184088> (20)
  *   D ref-organs/kidney-male-right.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-17c951000e11cd072ae82bdbc9c309e5882fc2010d6690676278bf563a65d4d6> (20)
  *   D ref-organs/lung-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-5919506be3e567ffd94f494ca10bb4c3219c369c9ec3e53ca3c3d0ca6c65b9d2> (20)
  *   D ref-organs/lung-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-de7f4154503c5859fffb245c4040723922b3ecf4022ae1defebb7ba59ea8699a> (20)
  *   D ref-organs/lymph-node-female-left.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-bdc4a83da525a5a9125e1fd9e9297423f4a76a54e0f45fde2fe212926d7357af> (20)
  *   D ref-organs/lymph-node-female-right.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-e6f2cc9a24aa2d49056c9c9fa59fc668529f1d4425dba811a38196f5e8503998> (20)
  *   D ref-organs/lymph-node-male-left.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-9de2e48a574324a9f39806c2b93956db2055e90106b57e0194ef8c2a3e8c237d> (20)
  *   D ref-organs/lymph-node-male-right.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-ff1a4ff196d0fcf60479affa5ff8f0efd66f5b54cf0edaba1e2e7ba45f80deb0> (20)
  *   D ref-organs/pelvis-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-62a593ad3b32b8bfb880aff8271e501416e33264f85cd04e0524b334e6ebe2d1> (20)
  *   D ref-organs/pelvis-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-644a8514e0c67a9633ffdf6ace26282ede4626579f4cf68f6aabc3283f073959> (20)
  *   D ref-organs/skin-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-1b32c3a84de5db0240ee9f2d78109727a94042094e57d908f411f721ee8d5721> (20)
  *   D ref-organs/skin-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-aeb3841187dbbfb684710301222034aef5998a8204a456c61c06ea65adab5dcc> (20)
  *   D ref-organs/spleen-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-7425fd2b386b3544861a9d3e1fc48b897cb80e3ca2210f047abd768e85786681> (20)
  *   D ref-organs/spleen-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-53dfa8dc626e59fd55be19fd652fbea4fd7024532c7a00a00e752f0d902f2bbe> (20)
  *   D ref-organs/thymus-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-98a731182afbb034f41b781a2ace215b2e8c4d54f5729e5037be6094a1496f70> (20)
  *   D ref-organs/thymus-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-c947f388c2cd317491692f5deb639562e5a2e21c4641246fe8ed2a9eef365f63> (20)
  *   D ref-organs/vasculature-female.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-686f8578c4cf5c1e5c28ed6be5a0dc53b14e28dbad286987cea8df558b9ef331> (20)
  *   D ref-organs/vasculature-male.md<https://github.com/hubmapconsortium/portal-docs/pull/60/files#diff-81d00754a263ed6ffba9fe2a68fe5c29c0c63b26321c1546aa1bae3ffbfd7582> (20)

Patch Links:

  *   https://github.com/hubmapconsortium/portal-docs/pull/60.patch
  *   https://github.com/hubmapconsortium/portal-docs/pull/60.diff

**Comment by mccalluc** [comment]
@lecross : Can you explicitly approve this PR, if it's ok?

**Comment by lecross** [comment]
Chuck, not sure what you need me to do. If you need me to simply state it is good to go, then yes. If you need me to do something in GitHub, then let me know. You can cancel the pull entirely. As far as I know, the files can be deleted from the server.

________________________________

**Comment by mccalluc** [comment]
@lecross -- In the future, please use the PR review process in github to indicate approval: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews

I have a lot of PRs out, and it makes my life easier if I can just look at the status icon to know whether a PR can be merged.

**Pull request merged**
